python3 run_sgd.py --dir out/ --dataset MNIST --data_path=data/ --model=Logistic --epochs=1000 --save_freq=25 --eval_freq=1 --lr_init 0.003 --wd=0.0001 --momentum=0 
python3 run_sgd.py --dir out/ --dataset MNIST --data_path=data/ --model=Logistic --epochs=1000 --save_freq=25 --eval_freq=1 --lr_init 0.003 --wd=0.0005 --momentum=0 
python3 run_sgd.py --dir out/ --dataset MNIST --data_path=data/ --model=Logistic --epochs=1000 --save_freq=25 --eval_freq=1 --lr_init 0.003 --wd=0 --momentum=0 
python3 run_sgd.py --dir out/ --dataset MNIST --data_path=data/ --model=Logistic --epochs=1000 --save_freq=25 --eval_freq=1 --lr_init 0.003 --wd=0.0001 --momentum=0 
python3 run_sgd.py --dir out/ --dataset MNIST --data_path=data/ --model=Logistic --epochs=1000 --save_freq=25 --eval_freq=1 --lr_init 0.003 --wd=0.0005 --momentum=0 
python3 run_sgd.py --dir out/ --dataset MNIST --data_path=data/ --model=Logistic --epochs=1000 --save_freq=25 --eval_freq=1 --lr_init 0.003 --wd=0 --momentum=0 
python3 run_sgd.py --dir out/ --dataset MNIST --data_path=data/ --model=Logistic --epochs=1000 --save_freq=25 --eval_freq=1 --lr_init 0.01 --wd=0.0001 --momentum=0 
python3 run_sgd.py --dir out/ --dataset MNIST --data_path=data/ --model=Logistic --epochs=1000 --save_freq=25 --eval_freq=1 --lr_init 0.01 --wd=0.0005 --momentum=0 
python3 run_sgd.py --dir out/ --dataset MNIST --data_path=data/ --model=Logistic --epochs=1000 --save_freq=25 --eval_freq=1 --lr_init 0.01 --wd=0 --momentum=0 
python3 run_sgd.py --dir out/ --dataset MNIST --data_path=data/ --model=Logistic --epochs=1000 --save_freq=25 --eval_freq=1 --lr_init 0.03 --wd=0.0001 --momentum=0 
python3 run_sgd.py --dir out/ --dataset MNIST --data_path=data/ --model=Logistic --epochs=1000 --save_freq=25 --eval_freq=1 --lr_init 0.03 --wd=0.0005 --momentum=0 
python3 run_sgd.py --dir out/ --dataset MNIST --data_path=data/ --model=Logistic --epochs=1000 --save_freq=25 --eval_freq=1 --lr_init 0.03 --wd=0 --momentum=0 
