python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00000.pt --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00000.pt --bn_train_mode_off --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00025.pt --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00025.pt --bn_train_mode_off --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00050.pt --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00050.pt --bn_train_mode_off --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00075.pt --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00075.pt --bn_train_mode_off --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00100.pt --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00100.pt --bn_train_mode_off --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00125.pt --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00125.pt --bn_train_mode_off --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00150.pt --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00150.pt --bn_train_mode_off --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00175.pt --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00175.pt --bn_train_mode_off --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00200.pt --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00200.pt --bn_train_mode_off --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00225.pt --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00225.pt --bn_train_mode_off --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00250.pt --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00250.pt --bn_train_mode_off --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00275.pt --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00275.pt --bn_train_mode_off --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00300.pt --basis 
python3 ../spectrum.py --curvature_matrix=hessian   --dataset=CIFAR100 --iters=100 --data_path=/home/diego/curvature/data/ --model=VGG16BN --ckpt=/home/diego/kfac-curvature/out/CIFAR100/VGG16BN/SGD/seed=1_lr=0.1_wd=0.0/checkpoint-00300.pt --bn_train_mode_off --basis 
